
spring:
  application:
    name: Chapter One

# Server
server:
  port: 9000

# Logs
logging:
  level:
    info.developia.learnspringbook.one: DEBUG

# Actuator
management:
  endpoint:
    configprops.enabled: true
    beans.enabled: true
    heapdump.enabled: true
    env.enabled: true
    health.enabled: true
    info.enabled: true
    metrics.enabled: true
    mappings.enabled: true
    httptrace.enabled: true
